/*
 * Copyright 2026 Viktor Rudebeck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package jots

import cats.Hash
import cats.syntax.all.*
import io.circe.Decoder
import io.circe.Encoder
import java.nio.charset.StandardCharsets.UTF_8
import jots.JwtException.InvalidSignedJwt
import scodec.bits.ByteVector

/**
  * A signed JSON Web Token (JWT) which has not been verified.
  *
  * The `String` representation is either parsed or generated by
  * using e.g. [[JwtBuilder#signWith]]. Unlike [[JwtBuilder]], the
  * [[SignedJwt]] does not allow for modifications.
  *
  * The [[SignedJwt]] should generally not be trusted unless it is
  * part of a [[VerifiedJwt]]. A [[SignedJwt]] can be verified by
  * using the [[SignedJwt#verifyWith]] method.
  */
sealed abstract class SignedJwt {

  /**
    * Returns the [[SignedJwtHeader]] for this signed token.
    */
  def header: SignedJwtHeader

  /**
    * Returns the [[SignedJwtClaims]] for this signed token.
    */
  def claims: SignedJwtClaims

  /**
    * Returns the [[JwtSignature]] for this signed token.
    */
  def signature: JwtSignature

  /**
    * Returns the bytes the signing algorithm should have signed.
    */
  def signedBytes: ByteVector

  /**
    * Returns a new [[JwtBuilder]] using the signed token contents.
    *
    * This enables using a signed token as the basis of a new token.
    */
  def toBuilder: JwtBuilder

  /**
    * Verifies the signed token using the provided verification.
    */
  def verifyWith[F[_]](verification: JwtVerification[F]): F[VerifiedJwt]

  /**
    * Returns the signed token in its `String` representation.
    *
    * Note that tokens are generally considered sensitive details.
    */
  def show: String
}

object SignedJwt {
  private final case class SignedJwtImpl(
    override val header: SignedJwtHeader,
    override val claims: SignedJwtClaims,
    override val signature: JwtSignature
  ) extends SignedJwt {
    override def signedBytes: ByteVector =
      ByteVector.view(show"$header.$claims".getBytes(UTF_8))

    override def toBuilder: JwtBuilder =
      JwtBuilder(header.toHeader, claims.toClaims)

    override def verifyWith[F[_]](verification: JwtVerification[F]): F[VerifiedJwt] =
      verification.verify(this)

    override def show: String =
      show"$header.$claims.$signature"

    override def toString: String =
      s"SignedJwt($header,$claims)"
  }

  /**
    * Returns a new [[SignedJwt]] from the specified header,
    * claims and signature.
    */
  def apply(
    header: SignedJwtHeader,
    claims: SignedJwtClaims,
    signature: JwtSignature
  ): SignedJwt =
    SignedJwtImpl(header, claims, signature)

  /**
    * Returns a new [[SignedJwt]] by parsing the specified
    * token in its `String` representation.
    */
  def fromString(signedJwt: String): Either[JwtException, SignedJwt] = {
    val headerEnd = signedJwt.indexOf('.')
    val claimsEnd = signedJwt.indexOf('.', headerEnd + 1)

    val wellFormed =
      headerEnd > 0 && claimsEnd > headerEnd + 1 && signedJwt.indices.forall { index =>
        index == headerEnd || index == claimsEnd || isBase64Url(signedJwt.charAt(index))
      }

    if (wellFormed) {
      val parsed =
        for {
          header <- SignedJwtHeader.fromString(signedJwt.substring(0, headerEnd))
          claims <- SignedJwtClaims.fromString(signedJwt.substring(headerEnd + 1, claimsEnd))
          signature <- JwtSignature.fromString(signedJwt.substring(claimsEnd + 1))
        } yield SignedJwt(header, claims, signature)

      parsed.leftMap(cause => new InvalidSignedJwt(cause = Some(cause)))
    } else Left(new InvalidSignedJwt(Some("token does not match expected pattern")))
  }

  /**
    * Alias for [[SignedJwt.fromString]].
    */
  def parse(signedJwt: String): Either[JwtException, SignedJwt] =
    fromString(signedJwt)

  private def isBase64Url(c: Char): Boolean =
    ('A' <= c && c <= 'Z') || ('a' <= c && c <= 'z') || ('0' <= c && c <= '9') || c == '-' || c == '_'

  implicit val signedJwtDecoder: Decoder[SignedJwt] =
    Decoder[String].emap(fromString(_).leftMap(_.message))

  implicit val signedJwtEncoder: Encoder[SignedJwt] =
    Encoder[String].contramap(_.show)

  implicit val signedJwtHash: Hash[SignedJwt] =
    Hash.fromUniversalHashCode
}
